In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
df = pd.read_csv("../data/raw/Bank-Customer-Churn.csv")

In [6]:
# Eliminar columnas que no sirven para nada
df = df.drop(columns=["RowNumber", "CustomerId", "Surname"])
df = df.drop(columns=["Complain"]) # no se aun ya que predice el churn, si todo va mal lo meto :/
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Satisfaction Score,Card Type,Point Earned
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,2,DIAMOND,464
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,3,DIAMOND,456
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,3,DIAMOND,377
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,5,GOLD,350
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,5,GOLD,425

In [ ]:
# Encoding de las variables categoricas
df["Gender"] = df["Gender"].map({
    "Male": 0,
    "Female": 1
})

df = pd.get_dummies(df, columns=["Geography"], drop_first=True) # drop_first=True si germany y spain son false es que es france

In [8]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Satisfaction Score,Card Type,Point Earned,Geography_Germany,Geography_Spain
0,619,1,42,2,0.00,1,1,1,101348.88,1,2,DIAMOND,464,False,False
1,608,1,41,1,83807.86,1,0,1,112542.58,0,3,DIAMOND,456,False,True
2,502,1,42,8,159660.80,3,1,0,113931.57,1,3,DIAMOND,377,False,False
3,699,1,39,1,0.00,2,0,0,93826.63,0,5,GOLD,350,False,False
4,850,1,43,2,125510.82,1,1,1,79084.10,0,5,GOLD,425,False,True

In [11]:
# separar columnas target
X = df.drop("Exited", axis=1)
y = df["Exited"]

In [ ]:
# ver el desbalance
print(y.value_counts(normalize=True) * 100)

Exited
0    79.62
1    20.38
Name: proportion, dtype: float64

In [20]:
# guardamos el df preparado para train test
df.to_csv("../data/processed/churn_processed.csv", index=False)

In [16]:
# pasamos a hacer traintest
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y # stratify para mantener la misma proporción de clases en train y test
)

In [14]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Satisfaction Score,Card Type,Point Earned,Geography_Germany,Geography_Spain
0,619,1,42,2,0.00,1,1,1,101348.88,1,2,DIAMOND,464,False,False
1,608,1,41,1,83807.86,1,0,1,112542.58,0,3,DIAMOND,456,False,True
2,502,1,42,8,159660.80,3,1,0,113931.57,1,3,DIAMOND,377,False,False
3,699,1,39,1,0.00,2,0,0,93826.63,0,5,GOLD,350,False,False
4,850,1,43,2,125510.82,1,1,1,79084.10,0,5,GOLD,425,False,True

In [17]:
# Escalado de las variables numéricas
scaler = StandardScaler()

numeric_cols = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "EstimatedSalary",
    "Satisfaction Score",   # los dejo para probar mas modelos, dependiendo del que coja los quito o no
    "Point Earned"          # los dejo para probar mas modelos, dependiendo del que coja los quito o no
]

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [ ]:
# guardado de los train test                                            || cambiar los escalados si va mal
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)